### ISSUE TITLE
ValueError: No Canalyst-II USB device found

### ISSUE THREAD

**Issue by ercansezdi** [projectgus/python-canalystii#1]
When I try to run it in any way, I get a response saying "ValueError: No Canalyst-II USB device found". My Canalyst-II device appears to be connected. I wonder what I did wrong.  Can you help me?

**Comment by projectgus** [comment]
@ercansezdi I can possibly help you. What operating system are you and using, and exactly how are you running it when you get this output?

**Comment by ercansezdi** [comment]
Hello @projectgus , the operating system I am currently using is Windows 10.
#####  my code  ####
#!/usr/bin/env python
import canalystii

dev = canalystii.CanalystDevice(bitrate=125000)

###### result  32bit python ####

Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\appc\canbus.py", line 4, in <module>
    dev = canalystii.CanalystDevice(bitrate=125000)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\canalystii\device.py", line 59, in __init__
    raise ValueError("No Canalyst-II USB device found")
ValueError: No Canalyst-II USB device found

#### result 64 bit python ###

Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\appc\canbus.py", line 4, in <module>
    dev = canalystii.CanalystDevice(bitrate=125000)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\canalystii\device.py", line 59, in __init__
    raise ValueError("No Canalyst-II USB device found")
ValueError: No Canalyst-II USB device found

###############
I want to give you some extra information. When I check my computer's device manager, I see that Canalyst-II is under custom usb and named winusb device. But I don't know how to report this.

**Comment by projectgus** [comment]
Thanks @ercansezdi, that's helpful.

Custom USB on Windows is a bit of a mess. python-canalystii uses [pyusb](https://pyusb.github.io/pyusb/) and on Windows pyusb uses the "libusb-win32" driver, not WinUSB. The easiest way to switch drivers is to use [Zadig](https://zadig.akeo.ie/):

1. Download Zadig and open it on your computer.
2. Select the Canalyst-II USB device in the dropdown.
3. Change "WinUSB" to "libusb-win32" and click the "Reinstall driver" button.

Fingers crossed that's all it needs! If necessary then you can use Zadig to swap the driver back to libusb-win32, as well.

**Comment by ercansezdi** [comment]
Hello @projectgus, sorry for being late. The problem was actually quite simple. Since I was running Python 64 bit, I was not able to communicate. I was able to read the data with Python 32 bit. Thank you for your help.

**Comment by projectgus** [comment]
Glad to hear it!
